name: breakpoint
description: A Flutter plugin to calculate the material design breakpoints.
version: 1.0.1
authors:
 - Flutter Community <community@flutter.zone>
 - Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/fluttercommunity/breakpoint
maintainer: Rody Davis (@AppleEducate)

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
